Repository Fekide/strapi-plugin-translate, pull requests merged in 2023-03, with the labels that each got.

#123 chore(playground): remove explicit dependency on plugin in playground
  playground/config/plugins.js
  playground/package.json
  yarn.lock
Labels: dependencies

#133 feat(provider): add libretranslate provider
  package.json
  providers/libretranslate/LICENSE
  providers/libretranslate/README.md
  providers/libretranslate/__mocks__/initStrapi.js
  providers/libretranslate/__mocks__/server.js
  providers/libretranslate/jest.config.js
  providers/libretranslate/lib/__tests__/client.test.js
  providers/libretranslate/lib/__tests__/libretranslate.test.js
  providers/libretranslate/lib/client/index.js
  providers/libretranslate/lib/constants.js
  providers/libretranslate/lib/get-service.js
  providers/libretranslate/lib/index.js
  providers/libretranslate/package.json
Labels: enhancement

#143 fix(admin): fix error with strapi v4.8
  plugin/admin/src/components/Usage/index.js
Labels: bug
